author: "Jonhnny Weslley"
description: "A DNS for local development"
filesets:
  includes:
  - README.md
  - LICENSE
  - ext
  excludes:
  - \.git
  - .*\.go
  depth: 3
settings:
  build: go install -v
